version: '3'

services:

  app_cter:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: imersao-fullcycle-next-cter
    environment:
      - NEXT_PUBLIC_BANK_NAME=CTER
      - NEXT_PUBLIC_BANK_CODE=002
      - NEXT_PUBLIC_NEST_API_URL=http://host.docker.internal:8002/api
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3002:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks: 
      - cter-network
  
networks: 
  cter-network:
    driver: bridge